### ISSUE TITLE
Créez les diagrammes de cas d'utilisations

### ISSUE THREAD

**Issue by charlesen** [un-sam-sauvage/P5_Blog_PHP_OC#1]
Dans cette première partie on va créer les diagrammes de cas d'utilisation

**Comment by charlesen** [comment]
Estimation : 0,5 j

**Comment by un-sam-sauvage** [comment]
1- Diagramme de cas d'utilisation : https://www.canva.com/design/DAFQOSi6nec/TCp0QZLPmm8rP1MiEMSOhg/
2- Diagramme de classe de la base de donée : https://www.canva.com/design/DAFSMMtLT6o/Ja3ccXZNKTMl7uhoJiqv2g/
