### ISSUE TITLE
Mise en place du MVC

### ISSUE THREAD

**Issue by un-sam-sauvage** [un-sam-sauvage/P5_Blog_PHP_OC#10]
Mettre en place le MVC en plaçant les fichiers au bon endroit et les appelant au bon moment ainsi qu'une bonne architecture de projet.

**Comment by charlesen** [comment]
Comme vu avec toi,

j'aimerais que cette issue nous permettre de décrire les étapes permettant l'affichage d'une page simple via notre framework MVC.

Supposons que l'on veuille afficher la page d'accueil accessible depuis l'url `/`

1. Toutes les requêtes sont d'abord intercepter par le fichier index.php : c'est notre FrontController
2. Dans ce fichier, on fait appelle au Router (Altorouter ou Router maison) : celui fait le lien entre l'url saisie dans le navigateur et une route configurée dans l'application
3. Le routeur nous donne accès au contrôleur (`HomeController`) et à la méthode (`home`) permettant l'affichage de la page d'accueil
4. Le dispatcher se charge d'instancier le contrôleur (`controller = new HomeController()` et d'exécuter la bonne méthode (`$controller->home()`)
5. La méthode home appelle une vue html (`echo "Page d'accueil"`
6. La page d'accueil est affichée à l'écran

Ces étapes pourront plus tard être complété par l'appel à une base de données grâce à ce qu'on appelle un Model.

**Comment by un-sam-sauvage** [comment]
branch already merged issue resolved
